export const APP_CONSTANTS = {
  APP_NAME: 'NEXUS IDE',
  APP_VERSION: '1.0.0',
  MIN_PASSWORD_LENGTH: 8,
  MAX_FILE_SIZE_MB: 10,
  MAX_PROJECT_FILES: 1000,
  SYNC_INTERVAL_MS: 30000,
  SESSION_TIMEOUT_MS: 3600000,
  OFFLINE_CACHE_TTL_MS: 86400000,
  SUPPORTED_LANGUAGES: [
    'javascript',
    'typescript',
    'python',
    'rust',
    'go',
    'java',
    'kotlin',
    'swift',
    'dart',
    'cpp',
    'c',
    'html',
    'css',
    'json',
    'yaml',
    'markdown',
  ] as const,
  STORAGE_KEYS: {
    AUTH_TOKENS: '@nexus/auth_tokens',
    USER_PROFILE: '@nexus/user_profile',
    CACHED_PROJECTS: '@nexus/cached_projects',
    EDITOR_SETTINGS: '@nexus/editor_settings',
    THEME_PREFERENCE: '@nexus/theme_preference',
    LAST_SYNC: '@nexus/last_sync',
  },
  NOTIFICATION_CHANNELS: {
    DEPLOYMENTS: 'deployments',
    COLLABORATION: 'collaboration',
    ERRORS: 'errors',
    GENERAL: 'general',
  },
} as const;
